name: aws-cli-ec2-steps-plugin
version: 1.0.0
rundeckPluginVersion: 1.2
author: alexh
date: Tue June 28 2017
providers:
  - name: aws-cli-ec2-start-instances-step
    service: WorkflowNodeStep
    title: 'aws / ec2 / start-instances'
    description: 'Starts the EC2 instance.'
    plugin-type: script
    script-interpreter: python -u
    script-file: ec2-start-instances
    script-args: ${config.instance-ids}
    config:
      - type: String
        name: instance-ids
        title: instance-ids
        description: 'One or more instance IDs.'
        required: true
      - type: String
        name: additional-info
        title: additional-info
      - type: String
        name: cli-input-json
        title: cli-input-json
        description: 'Performs service operation based on the JSON string provided.'
        renderingOptions:
          displayType: CODE
          codeSyntaxMode: json        
      - type: String
        name: generate-cli-skeleton
        title: generate-cli-skeleton 
        description: 'Prints a JSON skeleton to standard output without sending an API request.'      
      - type: Boolean
        name: dryrun
        title: dryrun
        description: 'Checks whether you have the required permissions for the action, without actually making the request, and provides an error response'
      - type: String
        name: access_key
        title: access_key
        description: 'Access Key ID'
        renderingOptions:
          grouping: secondary
          groupName: Credentials
      - type: String
        name: secret_access_key
        title: secret_access_key
        description: 'Secret access Key'
        renderingOptions:
          grouping: secondary
          groupName: Credentials
          selectionAccessor: "STORAGE_PATH"
          valueConversion: "STORAGE_PATH_AUTOMATIC_READ"
          storage-path-root: "keys"
      - type: String
        name: default_region
        title: default_region
        description: 'The default AWS region'
        renderingOptions:
          grouping: secondary
          groupName: Credentials
  - name: aws-cli-ec2-stop-instances-step
    service: WorkflowNodeStep
    title: 'aws / ec2 / stop-instances'
    description: 'Stops the EC2 instance.'
    plugin-type: script
    script-interpreter: python -u
    script-file: ec2-stop-instances
    script-args: ${config.instance-ids}
    config:
      - type: String
        name: instance-ids
        title: instance-ids
        description: 'One or more instance IDs.'
        required: true
      - type: String
        name: additional-info
        title: additional-info
      - type: String
        name: cli-input-json
        title: cli-input-json
        description: 'Performs service operation based on the JSON string provided.'
        renderingOptions:
          displayType: CODE
          codeSyntaxMode: json        
      - type: String
        name: generate-cli-skeleton
        title: generate-cli-skeleton 
        description: 'Prints a JSON skeleton to standard output without sending an API request.'      
      - type: Boolean
        name: dryrun
        title: dryrun
        description: 'Checks whether you have the required permissions for the action, without actually making the request, and provides an error response'
      - type: String
        name: access_key
        title: access_key
        description: 'Access Key ID'
        renderingOptions:
          grouping: secondary
          groupName: Credentials
      - type: String
        name: secret_access_key
        title: secret_access_key
        description: 'Secret access Key'
        renderingOptions:
          grouping: secondary
          groupName: Credentials
          selectionAccessor: "STORAGE_PATH"
          valueConversion: "STORAGE_PATH_AUTOMATIC_READ"
          storage-path-root: "keys"
      - type: String
        name: default_region
        title: default_region
        description: 'The default AWS region'
        renderingOptions:
          grouping: secondary
          groupName: Credentials