#!/usr/bin/env python
# rds-failover-db-cluster
import argparse
import os
import subprocess
import sys
import logging
import time

formatter = logging.Formatter()
logging.basicConfig(stream=sys.stderr, level=logging.INFO,
                    format='%(levelname)s: %(message)s')
log = logging.getLogger('rds-failover-db-cluster')


parser = argparse.ArgumentParser(description='Forces a failover for a DB Cluster.')
parser.add_argument('db_cluster_identifier', help='DB cluster identifier for existing cluster to force a failover for')
args = parser.parse_args()

COMMAND = ["aws", "rds", "failover-db-cluster", "--db-cluster-identifier", args.db_cluster_identifier]


if "RD_CONFIG_TARGET_DB_INSTANCE_IDENTIFIER" in os.environ:
    COMMAND.append("--target-db-instance-identifier")
    COMMAND.append(os.getenv("RD_CONFIG_TARGET_DB_INSTANCE_IDENTIFIER"))
if "RD_CONFIG_CLI_INPUT_JSON" in os.environ:
    COMMAND.append("--cli-input-json")
    COMMAND.append(os.getenv("RD_CONFIG_CLI_INPUT_JSON"))
if "RD_CONFIG_GENERATE_CLI_SKELETON" in os.environ:
    COMMAND.append("--generate-cli-skeleton")
    COMMAND.append(os.getenv("RD_CONFIG_GENERATE_CLI_SKELETON"))

if "RD_CONFIG_ACCESS_KEY" in os.environ:
    os.environ["AWS_ACCESS_KEY_ID"] = os.environ["RD_CONFIG_ACCESS_KEY"]
if "RD_CONFIG_SECRET_ACCESS_KEY" in os.environ:
	os.environ["AWS_SECRET_ACCESS_KEY"] = os.environ["RD_CONFIG_SECRET_ACCESS_KEY"]
if "RD_CONFIG_DEFAULT_REGION" in os.environ:
        os.environ["AWS_DEFAULT_REGION"] = os.environ["RD_CONFIG_DEFAULT_REGION"]


log.info("Executing: '%s' ..." % ' '.join(COMMAND))

try:
    retcode = subprocess.call(COMMAND)
    time.sleep(5)
    sys.exit(retcode)
except OSError as e:
    print >>sys.stderr, "Command error:", e
    sys.exit(1)
# Done
